#!/bin/bash
#SBATCH --time=3:00
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=4
#SBATCH --mem=4G
#SBATCH --partition=gpu

# Makes the julia binary available. This will depend on your HPC setup
module load julia

# Run the job with full optimisations. Add in --project="." if you have a
# Project/Manifest with dependencies
julia run.jl